//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLD.AppRegister.MVC_CRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppRegisterDBContext : DbContext
    {
        public AppRegisterDBContext()
            : base("name=AppRegisterDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<LaunchInput> LaunchInputs { get; set; }
        public virtual DbSet<RoleAccess> RoleAccesses { get; set; }
        public virtual DbSet<SearchTag> SearchTags { get; set; }
        public virtual DbSet<UserApp> UserApps { get; set; }
        public virtual DbSet<UserAppInput> UserAppInputs { get; set; }
        public virtual DbSet<UserAppSearchTag> UserAppSearchTags { get; set; }
        public virtual DbSet<UserSecondaryApp> UserSecondaryApps { get; set; }
    }
}
