//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLD.AppRegister.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAppInput
    {
        public int ID { get; set; }
        public int UserAppID { get; set; }
        public int LaunchInputID { get; set; }
        public string Value { get; set; }
    
        public virtual LaunchInput LaunchInput { get; set; }
        public virtual UserApp UserApp { get; set; }
    }
}
