//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLD.AppRegister.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecondaryApp
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public int PrimaryComponentID { get; set; }
        public int SecondaryComponentID { get; set; }
        public string Title { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Component Component1 { get; set; }
    }
}
