//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLD.AppExecution.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionThread
    {
        public int ID { get; set; }
        public string LaunchCommandLineJson { get; set; }
        public string LaunchInputsJson { get; set; }
        public int ExecutionStatus { get; set; }
        public string LockUserName { get; set; }
        public string LockUserID { get; set; }
        public Nullable<System.DateTime> LockDateTime { get; set; }
        public string RootComponentTitle { get; set; }
        public string ExecutingComponentTitle { get; set; }
        public int ComponentExecutingID { get; set; }
        public string ExecutingComponentsJson { get; set; }
        public string PendingOutcomeJson { get; set; }
    }
}
